// DO NOT EDIT THIS FILE
// Copy it to `config.js` and edit it
window.CONFIG = {
    defaultTemplateId: 'default', //This is the default template for 2 args1
    defaultAltTemplateId: 'defaultAlt', //This one for 1 arg
    templates: { //You can add static templates here
        'default': '<b>{0}</b>: {1}',
        'defaultAlt': '{0}',
        'print': '<pre>{0}</pre>',
        'example:important': '<h1>^2{0}</h1>'
    },
    fadeTimeout: 7000,
    suggestionLimit: 5,
    style: {
        background: 'rgba(52, 73, 94, 0)',
        width: '38%',
        height: '22%',
    }
};

var emojRange = [];
var emmmmoji = false;

function vEmojis(text) {
    var finalText = text;

    for (var i = 0; i < emojRange.length; i++) {
        var range = emojRange[i];
        var re = new RegExp(range[0], "g");
        finalText = finalText.replace(re, `<img class="iconChat" src="${range[1]}"></img>`);
    }

    return finalText;
}

function xEmoji(e) {
    $('#inputText').val($('#inputText').val() + "" + e);
    $("textarea").change();
}

window.addEventListener('message', function(event) {
    if (event.data.type == "Emojis") {
        if (event.data.emojis && !emmmmoji) {
            emojRange = event.data.emojis;
            emmmmoji = true;
        }
    }
});
